/**
 * The home page's copy, one object per locale. Kept apart from HomePage.tsx so
 * the Evolve surface defaults (homeSurfaces.ts) derive from exactly these
 * strings without importing the page and its three.js scene.
 */
export const HOME_T = {
  en: {
    // Hero
    heroH1Line1: 'Signal-to-code.',
    heroH1Line2: 'Ship what users actually need.',
    heroLede: 'RunHQ turns user feedback, telemetry, and support tickets into agent-built PRs — ready to review and ship. Come to work, approve the diff, merge.',
    ctaStartFree: 'Talk to us',
    ctaWatchDemo: 'Watch Demo',
    heroScreenshotAlt: 'RunHQ workspace — preview improvement task',
    heroScreenshotSmAlt: 'RunHQ feedback widget and latest updates',
    // Hero roles
    // Logos
    logosH: 'Trusted by engineering teams shipping with agents',
    // Pipeline section
    pipelineH2Line1: 'Why teams ship faster',
    pipelineH2Line2: 'on RunHQ.',
    pipelineDeck: 'Same feedback rate into both pipelines. The human handoff chain piles up at every step. Parallel coding agents drain the queue as fast as it arrives.',
    pipelineLabelBefore: 'BEFORE',
    pipelineLabelAfter: 'WITH RUNHQ',
    // Loop section
    loopH2Line1: 'Every release walks',
    loopH2Line2: 'the same loop.',
    loopDeck: 'Most coding-agent stacks stop at “the agent finished.” That’s the middle. RunHQ owns the ends — capture before, review after — so the middle can run unattended without scaring anyone.',
    // Loop stage 01 — Collect feedback
    loop1Title: 'Collect feedback',
    loop1Sub: 'One widget, no extra login.',
    loop1Body: 'Users and teammates send feedback straight from your product through an embedded widget — no separate account, no login wall. Each report lands in RunHQ with the page, the user, and repro context attached.',
    loop1Key1: 'Embedded widget',
    loop1Key2: 'No login wall',
    loop1Key3: 'Auto-context',
    // Loop stage 02 — Assign coding agents
    loop2Title: 'Assign coding agents',
    loop2Sub: 'Run them in parallel.',
    loop2Body: 'Assign tasks to your custom agents equipped with Claude Code, Cursor, Codex, or your own. RunHQ spawns processes in parallel while logging the important details for full transparency.',
    loop2Key1: 'BYO agent',
    loop2Key2: 'Parallel runs',
    loop2Key3: 'Full audit log',
    // Loop stage 03 — Review code
    loop3Title: 'Review code',
    loop3Sub: 'PRs land ready to read.',
    loop3Body: 'Every agent run lands as a clean pull request with diff, summary, and provenance attached — so reviewers can scan, comment, and approve in the GitHub flow they already use.',
    loop3Key1: 'GitHub PRs',
    loop3Key2: 'Inline diff',
    loop3Key3: 'One-click revert',
    // Loop stage 04 — Test + Deploy
    loop4Title: 'Test + Deploy',
    loop4Sub: 'Run the app before you ship.',
    loop4Body: 'RunHQ spins up a fully functioning server for every PR — its own URL, its own environment — so you can actually exercise the change end-to-end before it merges into the deploy pipeline you already run.',
    loop4Key1: 'Live preview env',
    loop4Key2: 'Per-PR sandbox',
    loop4Key3: 'Ships via your CD',
    // LoopCapture demo rows
    captureWho1: 'Jen K.',
    captureTxt1: 'Stripe portal drops session on Safari',
    captureWho2: 'Tomas R.',
    captureTxt2: 'Bulk archive in projects table',
    captureWho3: 'Andre B.',
    captureTxt3: 'Doc page returns 504 on cold start',
    // LoopAssign demo rows
    assignTask1: 'Stripe portal redirect',
    assignTask2: 'Bulk archive in projects',
    assignTask3: 'Doc page 504 on cold start',
    assignStatusRunning: 'running',
    assignStatusQueued: 'queued',
    assignStatusStandby: 'standby',
    assignLabel: 'assigned to',
    // LoopReview demo
    reviewPrH: 'PR #4821 · portal: cross-site cookies',
    reviewPrMeta: '+8 −3 · 1 file changed · ready for review',
    reviewBtnApprove: 'Approve',
    reviewBtnRequest: 'Request edits',
    reviewBtnRevert: 'Revert',
    // LoopDeploy demo
    deployPreviewLabel: 'preview:',
    deployPreviewV: 'pr-4821.runhq.dev · ready',
    deployTestsLabel: 'tests:',
    deployTestsV: '23 passed · 142s',
    deployDeployLabel: 'deploy:',
    deployDeployV: 'vercel · production',
    deployLiveLabel: 'live:',
    deployLiveV: 'portal.runhq.io · 200 OK',
    // Showcase — live boards
    showcaseEyebrow: 'Live boards',
    showcaseH2Line1: 'Real projects.',
    showcaseH2Line2: 'Running right now.',
    showcaseDeck: 'Every RunHQ project gets a public board — the same tickets, agent runs, and deploys you would run on your own product. Open one and watch the loop turn in real time.',
    showcaseOpenBoard: 'Open the live board',
    showcaseOpen: 'Open board',
    showcaseLive: 'live',
    showcaseStatTicketsWeek: 'tickets this week',
    showcaseStatContributors: 'contributors',
    showcaseStatDeploysWeek: 'deploys this week',
    showcaseStatTicketsTotal: 'total tickets',
    showcaseArrrName: 'ARRR',
    showcaseArrrTagline: 'A community shipping features by vote — hundreds of tickets a week, agents merging around the clock.',
    showcaseArrrArtAlt: 'ARRR — a voxel pirate game built on RunHQ',
    showcaseRunhqName: 'RunHQ',
    showcaseRunhqTagline: 'Our own board. We run RunHQ on RunHQ — every fix you see ships through this loop.',
    showcaseModdioName: 'Moddio',
    showcaseModdioTagline: 'A game platform routing player feedback straight into agent-built changes.',
    // CTA band
    ctaH1: 'Stop translating feedback by hand.',
    ctaH2: 'Start shipping it.',
    ctaBtnPrimary: 'Talk to us →',
    ctaBtnSecondary: 'Book a 20-min demo',
    ctaMeta1Strong: 'Live in 60 minutes.',
    ctaMeta1: 'Drop the widget, connect a source, ship before lunch.',
    ctaMeta2Strong: 'Audit log export.',
    ctaMeta2: 'PII strip at ingest. Every agent action versioned.',
    ctaMeta3Strong: 'Cancel anytime.',
    ctaMeta3: 'Take the audit log with you on the way out.',
    // Modal
    modalAriaLabel: 'Demo video',
    modalCloseLabel: 'Close demo video',
  },
  ko: {
    // Hero
    heroH1Line1: '시그널에서 코드로.',
    heroH1Line2: '사용자가 실제로 필요한 걸 배포하세요.',
    heroLede: 'RunHQ는 사용자 피드백, 텔레메트리, 지원 티켓을 에이전트가 만든 PR로 바꿔줍니다 — 검토하고 배포할 준비가 된 채로. 출근해서 diff 승인하고 머지하세요.',
    ctaStartFree: '문의하기',
    ctaWatchDemo: '데모 보기',
    heroScreenshotAlt: 'RunHQ 워크스페이스 — 개선 작업 미리보기',
    heroScreenshotSmAlt: 'RunHQ 피드백 위젯과 최신 업데이트',
    // Hero roles
    // Logos
    logosH: '에이전트와 함께 배포하는 엔지니어링 팀들이 신뢰합니다',
    // Pipeline section
    pipelineH2Line1: 'RunHQ에서 팀이',
    pipelineH2Line2: '더 빠르게 배포하는 이유.',
    pipelineDeck: '두 파이프라인에 같은 속도로 피드백이 들어옵니다. 사람 인수인계 방식은 매 단계마다 쌓이고, 병렬로 실행되는 코딩 에이전트는 들어오는 속도만큼 빠르게 큐를 비워냅니다.',
    pipelineLabelBefore: '이전',
    pipelineLabelAfter: 'RUNHQ와 함께',
    // Loop section
    loopH2Line1: '모든 릴리스는 같은',
    loopH2Line2: '루프를 따라갑니다.',
    loopDeck: '대부분의 코딩 에이전트 스택은 “에이전트 완료”에서 멈춥니다. 그건 중간 단계일 뿐입니다. RunHQ는 양쪽 끝 — 앞에서의 수집과 뒤에서의 리뷰 — 을 책임지기 때문에, 중간은 누구도 불안하지 않게 무인으로 돌아갈 수 있습니다.',
    // Loop stage 01 — Collect feedback
    loop1Title: '피드백 수집',
    loop1Sub: '위젯 하나, 추가 로그인 없음.',
    loop1Body: '사용자와 동료가 임베디드 위젯을 통해 제품에서 바로 피드백을 보냅니다 — 별도의 계정도, 로그인 장벽도 없습니다. 모든 리포트는 페이지, 사용자, 재현 컨텍스트가 함께 RunHQ로 도착합니다.',
    loop1Key1: '임베디드 위젯',
    loop1Key2: '로그인 장벽 없음',
    loop1Key3: '자동 컨텍스트',
    // Loop stage 02 — Assign coding agents
    loop2Title: '코딩 에이전트 할당',
    loop2Sub: '병렬로 실행하세요.',
    loop2Body: 'Claude Code, Cursor, Codex, 또는 직접 만든 커스텀 에이전트에 작업을 할당하세요. RunHQ는 프로세스를 병렬로 띄우면서 중요한 세부 사항을 모두 기록해 완전한 투명성을 제공합니다.',
    loop2Key1: '내 에이전트 연결',
    loop2Key2: '병렬 실행',
    loop2Key3: '전체 감사 로그',
    // Loop stage 03 — Review code
    loop3Title: '코드 리뷰',
    loop3Sub: 'PR이 바로 읽을 준비된 채로 도착합니다.',
    loop3Body: '모든 에이전트 실행은 diff, 요약, 출처가 첨부된 깔끔한 풀 리퀘스트로 도착합니다 — 리뷰어는 이미 쓰던 GitHub 플로우 안에서 훑고, 코멘트하고, 승인하면 됩니다.',
    loop3Key1: 'GitHub PR',
    loop3Key2: '인라인 diff',
    loop3Key3: '원클릭 되돌리기',
    // Loop stage 04 — Test + Deploy
    loop4Title: '테스트 + 배포',
    loop4Sub: '배포 전에 앱을 직접 돌려보세요.',
    loop4Body: 'RunHQ는 모든 PR에 대해 자체 URL과 자체 환경을 갖춘 완전한 서버를 띄워줍니다 — 그래서 이미 사용 중인 배포 파이프라인에 머지되기 전에 변경 사항을 엔드 투 엔드로 실제로 돌려볼 수 있습니다.',
    loop4Key1: '라이브 프리뷰 환경',
    loop4Key2: 'PR별 샌드박스',
    loop4Key3: '기존 CD로 배포',
    // LoopCapture demo rows
    captureWho1: 'Jen K.',
    captureTxt1: 'Safari에서 Stripe 포털 세션이 끊김',
    captureWho2: 'Tomas R.',
    captureTxt2: '프로젝트 테이블에서 일괄 아카이브',
    captureWho3: 'Andre B.',
    captureTxt3: '콜드 스타트 시 문서 페이지가 504 반환',
    // LoopAssign demo rows
    assignTask1: 'Stripe 포털 리다이렉트',
    assignTask2: '프로젝트 일괄 아카이브',
    assignTask3: '콜드 스타트 시 문서 페이지 504',
    assignStatusRunning: '실행 중',
    assignStatusQueued: '대기 중',
    assignStatusStandby: '대기',
    assignLabel: '할당 대상',
    // LoopReview demo
    reviewPrH: 'PR #4821 · portal: cross-site cookies',
    reviewPrMeta: '+8 −3 · 파일 1개 변경 · 리뷰 준비됨',
    reviewBtnApprove: '승인',
    reviewBtnRequest: '수정 요청',
    reviewBtnRevert: '되돌리기',
    // LoopDeploy demo
    deployPreviewLabel: '프리뷰:',
    deployPreviewV: 'pr-4821.runhq.dev · 준비됨',
    deployTestsLabel: '테스트:',
    deployTestsV: '23개 통과 · 142s',
    deployDeployLabel: '배포:',
    deployDeployV: 'vercel · production',
    deployLiveLabel: '라이브:',
    deployLiveV: 'portal.runhq.io · 200 OK',
    // Showcase — live boards
    showcaseEyebrow: '라이브 보드',
    showcaseH2Line1: '실제 프로젝트가',
    showcaseH2Line2: '지금 돌아가고 있습니다.',
    showcaseDeck: '모든 RunHQ 프로젝트에는 공개 보드가 있습니다 — 여러분이 자기 제품에서 돌릴 것과 똑같은 티켓, 에이전트 실행, 배포가 담겨 있죠. 하나 열어서 루프가 실시간으로 도는 걸 지켜보세요.',
    showcaseOpenBoard: '라이브 보드 열기',
    showcaseOpen: '보드 열기',
    showcaseLive: '라이브',
    showcaseStatTicketsWeek: '이번 주 티켓',
    showcaseStatContributors: '기여자',
    showcaseStatDeploysWeek: '이번 주 배포',
    showcaseStatTicketsTotal: '전체 티켓',
    showcaseArrrName: 'ARRR',
    showcaseArrrTagline: '투표로 기능을 배포하는 커뮤니티 — 매주 수백 개의 티켓, 24시간 내내 머지하는 에이전트.',
    showcaseArrrArtAlt: 'ARRR — RunHQ로 만든 복셀 해적 게임',
    showcaseRunhqName: 'RunHQ',
    showcaseRunhqTagline: '우리 자신의 보드. RunHQ는 RunHQ 위에서 돌아갑니다 — 여러분이 보는 모든 수정이 이 루프를 거쳐 배포됩니다.',
    showcaseModdioName: 'Moddio',
    showcaseModdioTagline: '플레이어 피드백을 에이전트가 만든 변경으로 곧장 연결하는 게임 플랫폼.',
    // CTA band
    ctaH1: '피드백을 손으로 옮기는 건 그만.',
    ctaH2: '바로 배포하세요.',
    ctaBtnPrimary: '문의하기 →',
    ctaBtnSecondary: '20분 데모 예약하기',
    ctaMeta1Strong: '60분 안에 라이브.',
    ctaMeta1: '위젯을 붙이고, 소스를 연결하고, 점심 전에 배포하세요.',
    ctaMeta2Strong: '감사 로그 내보내기.',
    ctaMeta2: '수집 단계에서 PII 제거. 모든 에이전트 액션 버전 관리.',
    ctaMeta3Strong: '언제든 해지.',
    ctaMeta3: '나갈 때 감사 로그를 그대로 가져가세요.',
    // Modal
    modalAriaLabel: '데모 영상',
    modalCloseLabel: '데모 영상 닫기',
  },
} as const;
